### ISSUE TITLE
Add Breakpoints Functionality to Glyphs

### ISSUE THREAD

**Issue by bushidocodes** [DecipherNow/gm-ui-components#109]
Moved from dashboard. Original visible at https://github.com/DecipherNow/gm-fabric-dashboard/issues/801

Per @shanberg:
-------------
Glyphs, IconFills, and IconBorders should accept a prop like `glyphCanvasSize` or `iconCanvasSize` from their parent, and render a path most appropriate for the available space.

I expect that most glyphs won't have more than one or two paths, but some will have many.

Ballparking the necessary canvas size breakpoints that a glyph path should be able to address...
`≥0px, ≥12px, ≥16px, ≥24px, ≥32px, ≥48px`

I'm curious what the performance implications would be if we allow the size to change on resize, rather than just first render.

**Comment by shanberg** [comment]
I think this is pretty out-of-scope for just about any project we'll ever work on. Closing.
