### ISSUE TITLE
Implement UI Themes based on Styled-Components and Styled-Themes

### ISSUE THREAD

**Issue by bushidocodes** [DecipherNow/gm-ui-components#110]
Moved from dashboard. Original visible at https://github.com/DecipherNow/gm-fabric-dashboard/issues/186

Per spmcbride1201
-------------
Architecturally, most of our themes should be implemented within our styled-components using styled-theming. This seems like it would be the best pattern for components that are easy to reuse in other projects.
https://www.styled-components.com/docs/tooling#styled-theming
https://github.com/styled-components/styled-theming

**Comment by shanberg** [comment]
@bushidocodes @kaitmore @tilleryd It may be time to take another look at this.

@kaitmore What are the limitations of the current basic form of theming we have in place via `StyleVariables.js`?

**Comment by shanberg** [comment]
OBE
