### ISSUE TITLE
What do we need to accomplish to be able to make this a dependency in `gm-fabric-dashboard`?

### ISSUE THREAD

**Issue by bushidocodes** [DecipherNow/gm-ui-components#112]
I've been reviewing the work that @kaitmore and @shanberg did in here for theming during the last Fracking Friday, and I kinda want to refocus our efforts on being able to extract components from `gm-fabric-dashboard`. 

It currently feels like we're walking backwards on a moving walkway at Reagan National. We try to walk to the end of the walkway, but each time we start work in this project, we have to pull organic changes from the dashboard back into here. Then we get a bit of time to improve things here in the component library, but we don't quite feel confident enough to make it a hard dependency of `gm-fabric-dashboard`, so things end up drifting further.

My suggestion is that we need to focus efforts on making the component library the authoritative UI source one component at a time.

**Comment by shanberg** [comment]
That’s a reasonable direction @spmcbride1201. The theming work was more speculative, hence its being a Fracking Friday effort and not a Maintenance Monday effort.

But I agree that the primary goal of further work here should be to get these two gears to really engage with each other, perhaps even on Try-hard Tuesday, Willpower Wednesday, and Thousand-hour Thursday.

**Comment by kaitmore** [comment]
The components that are still "stage 1" in my mind are:

- Tab and TabGroup
- Breadcrumbs
- Input
- Tooltip

Before we make this a dependency, I would like to:
- diagnose the AppFooter size
- cut a v1.5.0 release which contains the updated AppFooter, as well as new components ButtonGroup, Tab, and TabGroup

**Comment by kaitmore** [comment]
Sean also mentioned that there are issues with dependencies. We need to figure out what should be turned into a peer dependency.

**Comment by bushidocodes** [comment]
Last week, we made this a dependency in `gm-fabric-dashboard`, so closing this issue!
