### ISSUE TITLE
How should we handle fonts?

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-ui-components#119]
It seems like fonts are really blowing up our bundle size:

![image](https://user-images.githubusercontent.com/22768918/38952744-a3c77500-431a-11e8-8bb8-c8787089aa9e.png)

**Comment by bushidocodes** [comment]
When I use components from the library, they're not able to load GMMetropolis either... My opinion is that we should only use system fonts in the UI component library by default and allow users to use themes to override this with fonts that they install.
