### ISSUE TITLE
Add 'External Link' Icon

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-ui-components#129]
Add 'External Link' Icon

![screen shot 2018-04-25 at 11 45 55 am](https://user-images.githubusercontent.com/26534838/39257088-9fc07dbc-487e-11e8-94de-27481a6b5ca7.png)

**Comment by kaitmore** [comment]
@shanberg Is this something you could make for us?

**Comment by shanberg** [comment]
```<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><path d="M18 6.707l-4.146 4.147-.708-.708L17.293 6H13.5V5H19v5.525h-1V6.707zM16 11.5h1v4.934c0 .832-.673 1.566-1.5 1.566h-8c-.827 0-1.5-.734-1.5-1.566V8.5A1.5 1.5 0 0 1 7.5 7h5v1h-5a.5.5 0 0 0-.5.5v7.934c0 .298.246.566.5.566h8c.254 0 .5-.268.5-.566V11.5z" id="a"/></defs><g fill="none" fill-rule="evenodd"><mask id="b" fill="white"><use xlink:href="#a"/></mask><g mask="url(#b)" fill="#01BC26"><path d="M0 0h24v24H0z"/></g></g></svg>```

**Comment by kaitmore** [comment]
@shanberg wow that's some service :)

**Comment by kaitmore** [comment]
Closed by #250
