### ISSUE TITLE
Exported React components seem to have minified names

### ISSUE THREAD

**Issue by bushidocodes** [DecipherNow/gm-ui-components#135]
#  Bug 

## Expected Behavior

The React component that I import should be consistent with the name I use to import.

## Actual Behavior

The React component's name seems to be minified. This makes it impossible for `testcafe-react-selectors` to match on the component.

## Steps to Reproduce the Problem

  1. Start gm-fabric-dashboard
  2. Go to the Settings page
  3. Select the Clear Cache button using the React extension for Chrome dev tools
  
## Supporting Images or Videos

![image](https://user-images.githubusercontent.com/8700322/40846911-e4fa66c8-6588-11e8-8824-c0986f21ae4e.png)

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by kaitmore** [comment]
Closed by #141
