### ISSUE TITLE
Remove dead code in Breadcrumbs.story.js

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-ui-components#17]
It appears that `label` and `separator` are not used.

**Comment by kaitmore** [comment]
I am using them, but perhaps I don't need to store them in variables since there are only 2 stories

![screen shot 2017-10-06 at 1 17 04 pm](https://user-images.githubusercontent.com/22768918/31289964-ca0c3c52-aa98-11e7-8b28-3446bdf546fa.png)
