### ISSUE TITLE
Remove IE11 as a supported browser

### ISSUE THREAD

**Issue by bushidocodes** [DecipherNow/gm-ui-components#229]
Our browser support shifted to evergreen browsers, and this should be reflected on our README.

Our support matrix is as follows:
`  "browserslist": [
    "last 2 Chrome versions",
    "last 2 ChromeAndroid versions",
    "last 2 Safari versions",
    "last 2 iOS versions",
    "last 2 Firefox versions",
    "last 2 Edge versions"
  ],`

We should link our browser support matrix as a proper browserlist string.
http://browserl.ist/

**Comment by kaitmore** [comment]
http://browserl.ist/?q=last+2+Chrome+versions%2C+last+2+ChromeAndroid+versions%2C+last+2+Safari+versions%2C+last+2+iOS+versions%2C+last+2+Firefox+versions%2C+last+2+Edge+versions
