### ISSUE TITLE
Update date picker to display calendar as a popover

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-ui-components#245]
# Modification

## Which component do you want to modify?
DatePicker

## Will this modification effect the exisiting functionality?
No

## Describe your proposed change
At present, clicking on a date input displays the calendar inline and causes the parent component to expand vertically.  The proposition is to have the calendar appear as a popover to prevent the parent DOM element from changing size.

## Supporting Images, Videos, or Links
n/a

**Comment by kaitmore** [comment]
@tilleryd There is no DatePicker in this repo, I think we were using the react-datepicker library in the dashboard
