### ISSUE TITLE
Icons Update Request

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-ui-components#249]
A mid-stream update to the icons library.

[Icons Export.zip](https://github.com/DecipherNow/gm-ui-components/files/2287710/Icons.Export.zip)

**Comment by shanberg** [comment]
Here's a revised set

- Names updated to reflect icon relationships, rather than file structure
- Fixes to incorrect line widths and masking

[Icons Export 2.zip](https://github.com/DecipherNow/gm-ui-components/files/2294236/Icons.Export.2.zip)

**Comment by kaitmore** [comment]
Closed by #250
