### ISSUE TITLE
Fix the generation of story source

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-ui-components#269]
# 1. Bug 

## Expected Behavior
Story source for Storybook stories is generated upon story source changes.  Ideally we want to configure Storybook globally to reduce the proliferation of the `withInfo` decorator in throughout the stories.  @kaitmore and I made a brief attempt but ran into some issues.

## Actual Behavior
The story source is not being updated.

## Steps to Reproduce the Problem

  1. Simply make a change to story source, refresh and see that the old source remains.
  
## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by shanberg** [comment]
OBE
