### ISSUE TITLE
Default icon sizing

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-ui-components#275]
The current default sizing for Icons is to fill the parent container. In practice this only works when the parent container has a set width and height, which doesn't happen very often. This means that I almost always have to pass a `size="24px"` prop when using Icons.
 
2 solutions:
1) make the current implementation work better
2) change the default size to something reasonable like 24px

**Comment by shanberg** [comment]
My intention for the default size of glyphs is that they be appear _as much larger than a capitalized character as a capitalized character is larger than a lower case character._

This is the closest I've been able to come to a guiding principle for glyph size.

The glyphs are created in a 24px viewbox, and sized appropriately to the 14px default text size of the component library. To implement a good default size that responds to the context, let's generalize the sizing...  24px/14px = 1.714

So the default glyph size should be `1.714em`.

**Comment by kaitmore** [comment]
Closed by #288
