### ISSUE TITLE
Automate icon entry and modification

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-ui-components#277]
@kaitmore has nobly endured a lot of pain manually adding and updating icons in the set. It’s a lot of work, and very repetitive.

If we can automate this process, we may stand to gain a lot in terms of flexibility and psychological health.

We'd be automating...
- SVG file trimming and conversion to JS
- Test generation
- Storybook updates

@kaitmore may be able to add more here to say how long it takes to add new icons, and where the greatest benefits may be.

**Comment by kaitmore** [comment]
Closed by #375
