### ISSUE TITLE
Develop Storybook usage strategy

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-ui-components#283]
Our current Storybook scheme involves providing a single storybook file with each component. This keeps the storybook file and the component tied closely together, which is great. The downside I'm seeing now is that if we limit stories to components alone, we can't compose multiple components in a single story, which limits the illustrative/documentational power of Storybook.

I'd like us to agree on a consistent method of...
- Organizing like components within the Storybook stories list
- Writing stories for multiple components to demonstrate usage

**Comment by shanberg** [comment]
Per offline discussion, we'll be testing the following strategy...

- Storybook stories that exist for demonstration or illustration purposes are placed in a single folder at the root of the project source (called something like 'Demonstration').
- Demonstration stories may be composed of any number or kind of components. These stories should provide added value over the stories included in the component folders.
- Components in demonstration stories should be linked to their documentation stories via something like the Storybook Links add-on https://github.com/storybooks/storybook/tree/master/addons/links
- Component documentation stories should provide some type of category grouping via something like  this Storybook Chapters add-on https://github.com/Checkfront/react-storybook-addon-chapters, to provide improved clarity in the Storybook navigation. Components should remain at the top level of the project source folder.

**Comment by kaitmore** [comment]
I think we've figured out a solution with the Form component. I would expect to follow this strategy for similar components.
