### ISSUE TITLE
Upgrade to latest styled-components

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-ui-components#284]
# 2. Modification

## Which component do you want to modify?
Not a component, but the styled-components dependency.

## Will this modification effect the exisiting functionality?
No.

## Describe your proposed change
Upgrade to the latest styled-components to mitigate upcoming changes in v4.0.

Since version https://github.com/styled-components/styled-components/releases/tag/v3.4.3 a warning message was added that the `extend` API will be removed in 4.0.

```
Warning: The "extend" API will be removed in the upcoming v4.0 release. Use styled(StyledComponent) instead. You can find more information here: https://github.com/styled-components/styled-components/issues/1546
```

The `extend` API is used pretty sparingly already in `gm-ui-components`.  I only found one usage of it in `AppHeader.stories.js`.

We need to make sure we update the peerDependency to 3.4.x.

**Comment by kaitmore** [comment]
This is fixed in the 0.5.3 release 👍
