### ISSUE TITLE
Spinner should be responsive by default and provide a prop to pin a certain size

### ISSUE THREAD

**Issue by bushidocodes** [DecipherNow/gm-ui-components#334]
## Issue Template

You can use this template to raise three different types of issues. Please choose the appropriate section and delete the ones that do not apply.

1. Bug: Use this template to report a problem or inconsistency
2. Modification: Use this template to change an existing UI component. Keep in mind that components must be flexible enough that they can be used across a wide range of scenarios and shouldn't be constrained to a specific number of applications.
3. Proposal: Use this template to propose a new component

---------------------------------------------------------------------------------------

# 1. Bug 

## Steps to Reproduce the Problem

  1.
  2.
  3.
  
## Specifications

  - Version:
  - Platform:
  - Subsystem:

---------------------------------------------------------------------------------------

# 2. Modification

## Supporting Images, Videos, or Links

---------------------------------------------------------------------------------------

# 3. Proposal

## Does this pattern have state? 
If so, describe all possible states (e.g. Breadcrumb component with a collapsed or expanded state)

## Progressive enhancement
How does this pattern scale up? How will this pattern degrade in older browsers? Does the new component raise any accessibility concerns?

## Supporting Images, Videos, or Links

**Comment by shanberg** [comment]
@bushidocodes Are you looking for the spinner to switch between the vertical and horizontal modes according to screen size?

**Comment by kaitmore** [comment]
@shanberg @bushidocodes does #352 resolve this? I'm still a little confused by this issue.

**Comment by shanberg** [comment]
@kaitmore That PR is unrelated. I was just reimplementing the gradient effect.

@bushidocodes I don't think we can determine the intended spinner style by the size of the viewport. Here area few use cases I can think of to illustrate...
- "Loading App" spinner on a mobile device – large spinner.
- "Loading list items" in a dropdown on a mobile device – small spinner.
- "Logging In" on a desktop display – large spinner.
- "Loading list items" in a dropdown on a desktop display – small spinner.

Where possible, I definitely want to include smart defaults. I'm just worried we'd end up having to override the default in half of the use cases.
