### ISSUE TITLE
AppFooter shouldn't be `position: absolute` by default

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-ui-components#341]
## Which component do you want to modify?
AppFooter

## Will this modification effect the existing functionality?
Yes. Absolutely-positioned app footer behavior will have to be reimplemented if desired.

## Describe your proposed change
It’s quite weird for a component like the App Footer to force itself out of the page layout by default. This may be desired behavior in some circumstances. In situations where we can't make a positive determination about a property in at last the vast majority of use cases, I prefer we defer those decisions to the user of the component, or support a few specific use cases via props, rather than forcing a component user to override default styles.

**Comment by kaitmore** [comment]
I agree with this. As a default, components should always be neutral in terms of page layout.

**Comment by shanberg** [comment]
Closed by #460
