### ISSUE TITLE
Input component doesn't render props

### ISSUE THREAD

**Issue by 7ruth** [DecipherNow/gm-ui-components#348]
## Issue Template
# 1. Bug 

## Expected Behavior
When passing onChange and value props to Input component I expect them to be rendered.

## Actual Behavior
They are not rendered

## Steps to Reproduce the Problem

  1. import Input from "gm-ui-components"
  2. <Input onChange={e=>{console.log("hi")} value={"bye"} />
  3. Nothing is rendered
  
## Specifications

  - Version: latest

**Comment by kaitmore** [comment]
looks like this was just a bug in v0.5.3 and not latest, we should be good 👍
