### ISSUE TITLE
Remove margins from InputField

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-ui-components#360]
Component: 

## Will this modification effect the exisiting functionality?
No

## Describe your proposed change
- InputField and it's Label should not have margins

## Supporting Images, Videos, or Links
![image](https://user-images.githubusercontent.com/22768918/45754051-9320b080-bbe8-11e8-8786-55a80783b8d1.png)

**Comment by shanberg** [comment]
I added margins to inputs in the initial PR because I considered them a smart default. Looks like that was a bad assumption.

I'm wondering now if that's generalizable. Should all top-level library components have no external margin?

**Comment by kaitmore** [comment]
I think no margins is a good idea. There are probably some edge cases there but I can't think of any right now.
