### ISSUE TITLE
Refactor focus/active/hover states to be consistent

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-ui-components#371]
Right now we are using a brand color for focus/active/hover states. We should use blue across the board and refactor any inconsistencies. 

From @shanberg:
1. Brand color and interaction color should stay decoupled. Decipher Green isn’t likely to change anytime soon, but there are clear instances where the interaction color should probably not be green, and the interaction color is far more flexible than the brand color

2. Interaction color should _probably_ be 100% consistent across an application, but again we have more leeway with it and we can take more impressionistic interpretations of the original style, e.g. transforming it to a lighter or darker version of the same color, adding a separating space or line, etc.

**Comment by shanberg** [comment]
I believe this currently only affects the TableRow component.

**Comment by shanberg** [comment]
Closed by #480
