### ISSUE TITLE
Hide external links in footer

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-ui-components#373]
Component: `AppFooter`

## Will this modification effect the existing functionality?
Yes

## Describe your proposed change
- Add a boolean prop to conditionally hide external links to GitHub, Twitter, and LinkedIn.  Our government customers don't have access to the public internet and the links will be broken.

Relates to https://github.com/DecipherNow/gm-fabric-dashboard/issues/2448

## Supporting Images, Videos, or Links
- n/a

**Comment by tilleryd** [comment]
A longer term solution would be to allow some customization per deployment but that is out of scope here.

**Comment by tilleryd** [comment]
@shanberg @kaitmore For review/approval.  It's sort of just going through the motions to adhere to our process.

**Comment by shanberg** [comment]
I'm assuming this would be implemented as a prop in AppFooter, e.g.
`<AppFooter showSocialLinks={false} />`, and it defaults to true.

I approve this feature.

**Comment by tilleryd** [comment]
@shanberg I'd rather make the prop name more generic in anticipation of any external link, not just those that are for social media websites e.g. `showExternalLinks`.

**Comment by shanberg** [comment]
@tilleryd The Decipher logo is linked to deciphernow.com. `showExternalLinks` would be conceptually incomplete if it only addressed the social links.

How about `useExternalLinks` instead, where if true, the social links appear and the logo is linked, and if false the logo is just an image and the social links disappear?

**Comment by tilleryd** [comment]
@shanberg Good call.  I didn't catch the logo.  The more generalized prop `useExternalLinks` to satisfy 2 different use cases makes sense.
