### ISSUE TITLE
277-svg-loader Branch Observations

### ISSUE THREAD

**Issue by 7ruth** [DecipherNow/gm-ui-components#378]
Component (if applicable):

While testing 277-svg-loader (PR #375 ) following was identified (I don't know what was desired behavior and what I am expected to fix on my end as the result of the changes)

## Steps to Reproduce the Problem:

1. Pack 277-svg-loader branch locally
2. Drag it over to gm-data-ui (drive-next) root  
3. npm install gm-ui-components@0.6.1.tgz
4. restart all of gm-data-ui docker image for changes to take effect

## Supporting Images or Videos
1. Button's 'jiggle'/'resize' on interaction. Its not obvious when you click, but very obvious when you tab over them, video:

Video #1
[buttonJiggle.mov.zip](https://github.com/DecipherNow/gm-ui-components/files/2516306/buttonJiggle.mov.zip)

Video #2 
[searchFilters.mov.zip](https://github.com/DecipherNow/gm-ui-components/files/2516341/searchFilters.mov.zip)

2. FieldInput which replaced Input has different default causing extended components to have different size (in the below video, the Description field (the large one) is based on FieldInput

3. The 'jiggle' is present when you tab into the User input (second input in the video)(this component in the root of it also based on FieldInput, I suspect its due to the transition to having a border that appear around the input after the delay (I was under the impression we prefer to use shadow-box in house because it doesn't add px)

4. The checkboxes displace other things inside shared divs (last item in the video). Looks like its due to flex: auto property (just as a test, setting it to flex: 0 0 auto, pretty much fixed everything in the vid #2)

Video # 3
[Buttons.mov.zip](https://github.com/DecipherNow/gm-ui-components/files/2516384/Buttons.mov.zip)

5. Jiggling buttons and outline changes. The drop down panel and the buttons within it are based on the Button component.

- Version: gm-ui-comp 0.6.1

**Comment by kaitmore** [comment]
Resolved by #381
