### ISSUE TITLE
New Icon Request:  IconChevronTopDouble,   IconChevronBottomDouble,

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-ui-components#408]
Component: IconChevronTopDouble,   IconChevronBottomDouble,

## Describe the new component

- IconChevronTopDouble,   IconChevronBottomDouble

## In what context will the pattern be used?

- Scroll Up, Scroll Down Jump

## Does this pattern have state?

If so, describe all possible states (e.g. Breadcrumb component with a collapsed or expanded state)

- Similar to existing IconChevronLeftDouble and IconChevronRightDouble

## Progressive enhancement

How does this pattern scale up? How will this pattern degrade in older browsers? Does the new component raise any accessibility concerns?

- N/A

## Supporting Images, Videos, or Links

![Screen Shot 2019-04-02 at 11 59 17 AM](https://user-images.githubusercontent.com/26534838/55417480-c8ff0400-553e-11e9-9486-0018616ef98b.png)

**Comment by tilleryd** [comment]
@karinakeen This makes perfect sense.
@shanberg I assume you can knock this out super quick since we have left and right double chevrons.
@kaitmore I think we should target a release this Friday.

**Comment by kaitmore** [comment]
@tilleryd Sounds good
