### ISSUE TITLE
Spinner is buggy

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-ui-components#409]
Component (if applicable): Spinner

## Expected Behavior
![Apr-09-2019 17-21-19](https://user-images.githubusercontent.com/22768918/55836217-f4a85e00-5aeb-11e9-8798-f3fa41359800.gif)

## Actual Behavior

In Chrome and Safari, the animation doesn't work most of the time. 

When it does work, the speed is often inconsistent (lagging, freezing)

Chrome:
![image](https://user-images.githubusercontent.com/22768918/55835696-87e09400-5aea-11e9-9383-47842a5a480b.png)

Safari
![image](https://user-images.githubusercontent.com/22768918/55835676-7ac3a500-5aea-11e9-8cd1-c9afd827b195.png)

## Steps to Reproduce the Problem

1. Load up the dashboard and notice
2. 
3.

## Specifications

- Version:
- Platform:
- Subsystem:

**Comment by shanberg** [comment]
The issue in Chrome is interesting. It seems to disregard all but the first color stop when the stroke width is set to 1 or less. Setting the stroke width to 1.0001 seems to solve the color stops issue in Chrome.

**Comment by shanberg** [comment]
The spinner shouldn't cause any rendering performance issues.
Chrome and Safari both rendered over 200 spinners on a page without stuttering.

Maybe charts are causing the stuttering?

**Comment by kaitmore** [comment]
Closed by #430
