### ISSUE TITLE
Clicking Layout, Color, Typography in the Styles > Styles view causes white screen

### ISSUE THREAD

**Issue by 7ruth** [DecipherNow/gm-ui-components#417]
Component (if applicable):

## Expected Behavior

- I am not sure whats the best behavior should be, but not a white screen.

## Actual Behavior

- Clicking on one of the tabs in the Styles > Styles section (Layout, Color, Typography) causes a white screen

## Steps to Reproduce the Problem

1. Click on Styles section
2. Click on Styles sub-section
3. Click on one of the tabs 

## Supporting Images or Videos
![image](https://user-images.githubusercontent.com/10719152/56502661-24d70000-64e1-11e9-8dfe-05b065c3a3c0.png)

## Specifications

- Version:
- Platform:
- Subsystem:

**Comment by kaitmore** [comment]
thanks for reporting!
