### ISSUE TITLE
Global CSS Proposal

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-ui-components#418]
Component: 

## Describe the new component

- A baseline CSS to align, standardize, and promote re-use of the same styles for all Grey Matter UIs.

## In what context will the pattern be used?

- Imported into apps as a styled-component that ostensibly be used to reset and/or apply a consistent set of styles.

See React95 for inspiration:
https://github.com/arturbien/React95
https://github.com/arturbien/React95/blob/master/src/components/common/reset.js.

## Does this pattern have state?

If so, describe all possible states (e.g. Breadcrumb component with a collapsed or expanded state)

- No

## Progressive enhancement

How does this pattern scale up? How will this pattern degrade in older browsers? Does the new component raise any accessibility concerns?

- For the Grey Matter product we need to support these browsers:

  | Windows | MacOS | Linux | Android | iOS
-- | -- | -- | -- | -- | --
Chrome (latest) | x | x | x | x |  
Chrome (latest - 1) | x | x | x | x |  
Firefox (latest) | x | x | x |   |  
Firefox (latest - 1) | x | x | x |   |  
Edge (latest) | x |   |   |   |  
Edge (latest - 1) | x |   |   |   |  

## Supporting Images, Videos, or Links

- n/a

**Comment by shanberg** [comment]
Per conversation with @tilleryd and @kaitmore, I think this should begin as a reimplementation of the styles currently in injectGlobal in the Dashboard project.

**Comment by shanberg** [comment]
Closed by #443
