### ISSUE TITLE
Expose content of style folder (styleFunctions & styleVariables)

### ISSUE THREAD

**Issue by 7ruth** [DecipherNow/gm-ui-components#419]
Component: styleFunctions & styleVariables

## Describe the new component

- New components will encompass style/styleFunctions & style/styleVariables

## In what context will the pattern be used?

- These components will be used in other gm-ui-xx libs and gm projects

## Does this pattern have state?

- No

## Progressive enhancement

How does this pattern scale up? How will this pattern degrade in older browsers? Does the new component raise any accessibility concerns?

- More variables and functions may be added over time, this will be a great way to centralize things

**Comment by kaitmore** [comment]
Closed by #422
