### ISSUE TITLE
Rename container subcomponents to use consistent term

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-ui-components#432]
Wrapper/container subcomponents are using inconsistent terms for the same thing.

I propose we land on a single term, `Wrap`, to apply to all cases where we're currently using `Container`, `Wrap`, or `Wrapper`.

_`Wrap`_ merely because it's short and already in use in several components, and doesn't carry too much semantic baggage.

**Comment by tilleryd** [comment]
Let's not forget `Rapper`.

![icet](https://user-images.githubusercontent.com/2581080/57021875-6c553e80-6bfb-11e9-8126-27067416d865.jpg)

**Comment by shanberg** [comment]
This is a little more complex than I anticipated. I think we should pick a few representative components and work through the issues that come up together.

E.g....
- What about wrappers that get exported use on their own?
- Should this be part of a larger refactor where we clean up all subcomponent prefixes?
- Are there conventions in the larger community we should be leaning on here?

**Comment by shanberg** [comment]
#491

**Comment by shanberg** [comment]
Closed by #491
