### ISSUE TITLE
Release v0.8.1

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-ui-components#433]
Requirements:

- [x] Run Storybook and ensure that the changes since the last release are working as intended
- [x] `npm link` this project and smoke test
- [x] Publish to NPM

**Comment by dgoldstein1** [comment]
@tilleryd @kaitmore 

https://github.com/DecipherNow/gm-ui-components/releases/tag/v0.8.1

**Comment by kaitmore** [comment]
@dgoldstein1 Thanks David. I will go ahead and release on NPM.

**Comment by kaitmore** [comment]
Released 0.8.1 https://www.npmjs.com/package/gm-ui-components
