### ISSUE TITLE
Button type doesn't do anything for secondary

### ISSUE THREAD

**Issue by dance-dance-banana-frenzy** [DecipherNow/gm-ui-components#434]
Component (if applicable):

Button

## Expected Behavior

- setting button type to secondary should show secondary color

## Actual Behavior

- does nothing. 
- Button propTypes for `type` shows **secondary** is valid
- ButtonWrap propTypes `type` doesn't show **secondary**
- generateButtonStyle doesn't handle **secondary**

## Steps to Reproduce the Problem

```html
<Button type="secondary" label="secondary" style={{borderRadius: "9999px"}} />
```
## Supporting Images or Videos

<img width="308" alt="Screen Shot 2019-05-07 at 12 35 31 PM" src="https://user-images.githubusercontent.com/47341218/57316825-b25f4600-70c4-11e9-9256-32db8294ff15.png">

https://github.com/DecipherNow/gm-ui-components/blob/master/src/components/Button/components/ButtonWrap/utils/generateButtonStyle.js

## Specifications

- Version:
- Platform:
- Subsystem:

**Comment by shanberg** [comment]
I think the answer here is to remove `secondary` unless we can come up with a solid reason to keep it.
