### ISSUE TITLE
Button - support type for all background colors (A, B, and C)

### ISSUE THREAD

**Issue by dance-dance-banana-frenzy** [DecipherNow/gm-ui-components#435]
Component: 

## Will this modification effect the existing functionality?
No

## Describe your proposed change

- Button already supports COLOR_BACKGROUND_A when type="default", "secondary" or any unknown value
- Add type so that button can appear as COLOR_BACKGROUND_B (See bug #434 for "secondary")
- Add type so that button can appear as COLOR_BACKGROUND_C

## Supporting Images, Videos, or Links

-

**Comment by shanberg** [comment]
'Types' are intended to support specific interaction types, and are not a proxy for the background color.

I recommend extending the Button component if you want to apply custom styles.

**Comment by dance-dance-banana-frenzy** [comment]
Hmm... The button exposing "secondary" as a valid type doesn't make sense in this case.

**Comment by shanberg** [comment]
OBE Replaced with #436
