### ISSUE TITLE
Add `dangerouslySetColor` prop to Button to allow custom colors

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-ui-components#436]
Component: Button

## Will this modification effect the existing functionality?
No

## Describe your proposed change

- Provide a prop to set the baseColor, irrespective of the theme-set Type color.

**Comment by dance-dance-banana-frenzy** [comment]
Except that it will accept a color `function generateButtonStyle(theme, baseColor, renderBorder) {`

**Comment by shanberg** [comment]
Closed by #435
