### ISSUE TITLE
SVG loader breaks non-Icon SVG components

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-ui-components#446]
I tried to add an SVG unrelated to icons, and the webpack SVG template kept trying to parse it and import `components/Icon', which kept me from being able to use my SVG.

Is it possible to only apply that template to SVGs in an /Icons or /Glyphs folder?

**Comment by kaitmore** [comment]
Ah, good find Stuart. I will update webpack.

**Comment by kaitmore** [comment]
closed by #447
