### ISSUE TITLE
Fix snapshot tests

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-ui-components#451]
Updating to v4 broke our snapshot testing. We should keep an eye on this issue and update jest-styled-components and enzyme when it's resolved: https://github.com/styled-components/jest-styled-components/issues/191

**Comment by shanberg** [comment]
In the meantime, should we allow pushing up changes with broken snapshots?

**Comment by kaitmore** [comment]
I think "broken" was the wrong word.. more like "useless" :) Snapshot tests should still pass.
