### ISSUE TITLE
Button font sizes are mismatched

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-ui-components#474]
Component (if applicable): Button (`generateButtonSize` util)

## Expected Behavior

- Button sizes should have proper font size
- `XL` size buttons should use `FONT_SIZE_LG`.
- `LG` size buttons should use `FONT_SIZE_MD`.
- (Making the names make more sense is a separate issue.)

## Actual Behavior

- XL and LG size buttons both use FONT_SIZE_LG.

**Comment by tilleryd** [comment]
What about FONT_SIZE_XL, FONT_SIZE_L, FONT_SIZE_M, etc?  Why would XL map to FONT_SIZE_LG?

**Comment by shanberg** [comment]
@tilleryd 
> (Making the names make more sense is a separate issue.)

That will require a refactor, where this PR is just a fix for the visible symptom.
The fundamental issue is a lack of a coherent internal language for sizing, and that's quite a bit more work to fix.

**Comment by shanberg** [comment]
Closed by #476
