### ISSUE TITLE
<Collapse> should be controllable

### ISSUE THREAD

**Issue by dgoldstein1** [DecipherNow/gm-ui-components#504]
Component: 

## Will this modification effect the existing functionality?

Oui

## Describe your proposed change

- the `Collapse` component should have an option to be more controllable. Instead of tucking the onClick handler into the header, there should be an option to pass `isOpen`, `openSection` and `onClick(componentClicked)` which gives more control to the parent component.

## Supporting Images, Videos, or Links

https://github.com/DecipherNow/gm-dashboard/issues/3077
-

**Comment by kaitmore** [comment]
Closed by #505
