### ISSUE TITLE
Support nested collapse

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-ui-components#507]
Component: 

## Will this modification effect the existing functionality?
No

## Describe your proposed change

- Add a prop to Collapse called `bodyProps` so that we can pass styles to the content wrapper for edge case scenarios like nested collapse

**Comment by kaitmore** [comment]
If we think that nested collapse is a core use case that we want to support, we could also add a prop like `nestedCollapse`

**Comment by tilleryd** [comment]
I liked a `nestedCollapse` prop better because it solves a very clear use case. In the future if start to see more uses cases for overriding styles then we can add `bodyProps`.
