### ISSUE TITLE
Add Nav Tab Component

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-ui-components#86]
**MVP**
- Nav Tab Group component
    - Controls state of direct descendants

- Nav Tab component
    - States
        - Active
    - Label

---

**Further Development**
- Nav Tab Group Component
    - Controls state of direct descendants
    - Uses props to generate Nav Tab components
- Nav Tab component
    - States
        - Active
        - Disabled
    - Label
    - Icon

**Comment by kaitmore** [comment]
Closed by #87
