### ISSUE TITLE
Bring Table component in from the Fabric dashboard

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-ui-components#89]

**Comment by kaitmore** [comment]
@shanberg Do we still want to do this now that we have the gm-data Table?

**Comment by shanberg** [comment]
I believe @bushidocodes is currently working on an update to the Fabric table component that may include improvements to the layout and drawer functionality. These could be separate components, or we could try to combine the best of each and hide unnecessary features behind props.

**Comment by shanberg** [comment]
OBE
