### ISSUE TITLE
Clarify Input component usage

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-ui-components#97]
If we have multiple types of inputs, should these be differentiated with a prop, or should they be totally separate components?

**Comment by bushidocodes** [comment]
It seems like they should be different components entirely. The way vanilla HTML <input> tags work with the `type` attribute is pretty strange. Each type has their own weird semi-standards hooks for styling. I'm curious what @shanberg and @tilleryd think.

**Comment by shanberg** [comment]
I think each should be a separate component, and that we should roughly correspond to the HTML5 element names to limit confusion and searching.

`InputText`,
`InputPassword`,
`InputNumber`,
`InputMonth`,
`Select`,
`TextArea`,

etc.

There are a lot of these.

**Comment by shanberg** [comment]
at @bushidocodes's recommendation, I'm looking at https://www.npmjs.com/package/formik for ideas...

**Comment by shanberg** [comment]
I'll target these HTML elements in a first pass. We can then use these simple components as reference when we need to upgrade one or another to something more complex like `react-select`, and I'll keep the markup straightforward to minimize barriers to upgrading all the components to something like Formik.

More controls that aren't supported in vanilla HTML may need to be added in the future (toggle switches, toggle button groups, multiselects, etc.), so this should not be taken as a comprehensive list.
- fieldset
- select
- checkbox
- radio button
- textarea
- Input type="text"
- Input type="password"
- Input type="range"
- Input type="number"
- Input type="search"
- Input type="email"
- Input type="tel"
- Input type="url"
- Input type="range"

With the following CSS states where applicable...
- :hover
- :focus
- :active
- :valid
- :invalid
- :empty
- :default
- :checked
- :indeterminate
- :not(:checked):not(:indeterminate):not(:default)
- :disabled
- [readonly]
- :required

**Comment by shanberg** [comment]
Closed by #335
